export const RESOURCE_TYPE_LABELS = {
  ec2_instance: "EC2 Instance",
  s3_bucket: "S3 Bucket",
  rds_instance: "RDS Instance",
  ebs_volume: "EBS Volume",
  elastic_ip: "Elastic IP",
  security_group: "Security Group",
  snapshot: "EBS Snapshot",
  iam_role: "IAM Role",
  lambda_function: "Lambda Function",
  nat_gateway: "NAT Gateway",
  load_balancer: "Load Balancer",
  dynamodb_table: "DynamoDB Table",
  vpc: "VPC",
  auto_scaling_group: "Auto Scaling Group",
  ecs_cluster: "ECS Cluster",
  eks_cluster: "EKS Cluster",
  elasticache_cluster: "ElastiCache Cluster",
  sqs_queue: "SQS Queue",
  sns_topic: "SNS Topic",
  secret: "Secrets Manager",
  api_gateway: "API Gateway",
  aurora_cluster: "Aurora Cluster",
  cloudformation_stack: "CloudFormation Stack",
  eventbridge_rule: "EventBridge Rule",
  ecr_repository: "ECR Repository",
  internet_gateway: "Internet Gateway",
  cloudwatch_alarm: "CloudWatch Alarm",
  redshift_cluster: "Redshift Cluster",
};

export const STATUS_BADGE = {
  CRITICAL: "bg-red-500/20 text-red-400 border-red-500/30",
  WARNING: "bg-amber-500/20 text-amber-400 border-amber-500/30",
  HEALTHY: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
  ORPHANED: "bg-slate-500/20 text-slate-400 border-slate-500/30",
};

export const SUPPORTED_REGIONS = [
  { id: "us-east-1",      label: "US East (N. Virginia)" },
  { id: "us-east-2",      label: "US East (Ohio)" },
  { id: "us-west-1",      label: "US West (N. California)" },
  { id: "us-west-2",      label: "US West (Oregon)" },
  { id: "eu-west-1",      label: "Europe (Ireland)" },
  { id: "eu-west-2",      label: "Europe (London)" },
  { id: "eu-central-1",   label: "Europe (Frankfurt)" },
  { id: "ap-southeast-1", label: "Asia Pacific (Singapore)" },
  { id: "ap-southeast-2", label: "Asia Pacific (Sydney)" },
  { id: "ap-northeast-1", label: "Asia Pacific (Tokyo)" },
  { id: "ca-central-1",   label: "Canada (Central)" },
  { id: "sa-east-1",      label: "South America (São Paulo)" },
];

// Maps AWS Cost Explorer service names to the resource `type` values our scanners use
// Used to attribute service-level CE costs to individual resources
export const CE_SERVICE_TO_RESOURCE_TYPES = {
  "Amazon Elastic Compute Cloud - Compute": ["ec2_instance"],
  "Amazon EC2 - Other": ["ebs_volume", "elastic_ip", "snapshot"],
  "Amazon Simple Storage Service": ["s3_bucket"],
  "Amazon Relational Database Service": ["rds_instance"],
  "Amazon Aurora MySQL": ["aurora_cluster"],
  "Amazon Aurora PostgreSQL": ["aurora_cluster"],
  "AWS Lambda": ["lambda_function"],
  "Amazon DynamoDB": ["dynamodb_table"],
  "Amazon Virtual Private Cloud": ["vpc", "nat_gateway", "internet_gateway"],
  "Amazon API Gateway": ["api_gateway"],
  "AWS Secrets Manager": ["secret"],
  "Amazon ElastiCache": ["elasticache_cluster"],
  "Amazon Elastic Container Service": ["ecs_cluster"],
  "Amazon Elastic Kubernetes Service": ["eks_cluster"],
  "Amazon Redshift": ["redshift_cluster"],
  "Amazon Simple Queue Service": ["sqs_queue"],
  "Amazon Simple Notification Service": ["sns_topic"],
  "Amazon CloudWatch": ["cloudwatch_alarm"],
  "AWS CloudFormation": ["cloudformation_stack"],
  "Amazon Elastic Container Registry": ["ecr_repository"],
  "Amazon EventBridge": ["eventbridge_rule"],
  "Elastic Load Balancing": ["load_balancer"],
  "Amazon EC2 Auto Scaling": ["auto_scaling_group"],
};

