export const RESOURCE_TYPE_LABELS = {
  ec2_instance: "EC2 Instance",
  s3_bucket: "S3 Bucket",
  rds_instance: "RDS Instance",
  ebs_volume: "EBS Volume",
  elastic_ip: "Elastic IP",
  security_group: "Security Group",
  snapshot: "EBS Snapshot",
  iam_role: "IAM Role",
  lambda_function: "Lambda Function",
  nat_gateway: "NAT Gateway",
  load_balancer: "Load Balancer",
  dynamodb_table: "DynamoDB Table",
  vpc: "VPC",
  auto_scaling_group: "Auto Scaling Group",
  ecs_cluster: "ECS Cluster",
  eks_cluster: "EKS Cluster",
  elasticache_cluster: "ElastiCache Cluster",
  sqs_queue: "SQS Queue",
  sns_topic: "SNS Topic",
  secret: "Secrets Manager",
  api_gateway: "API Gateway",
  aurora_cluster: "Aurora Cluster",
  cloudformation_stack: "CloudFormation Stack",
  eventbridge_rule: "EventBridge Rule",
  ecr_repository: "ECR Repository",
  internet_gateway: "Internet Gateway",
  cloudwatch_alarm: "CloudWatch Alarm",
  redshift_cluster: "Redshift Cluster",
};

export const STATUS_BADGE = {
  CRITICAL: "bg-red-500/20 text-red-400 border-red-500/30",
  WARNING: "bg-amber-500/20 text-amber-400 border-amber-500/30",
  HEALTHY: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
  ORPHANED: "bg-slate-500/20 text-slate-400 border-slate-500/30",
};
